[project]
name = "os-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "stable-baselines3>=2.7.1",
    "torch>=2.10.0",
]
